name: Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify the Python version for your Flask app

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure your dependencies are listed in requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flask1234'  # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}  # Set this secret in your GitHub repository
